name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: go mod download

      - name: Build application
        run: |
          cd cmd/openapi-mock
          go build -v
          cd ../..

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.26

      - name: Run tests
        run: go test -v $(go list ./... | grep -v vendor)
